DECOUNCE_TYPE = sym_defer_pr

ENCODER_ENABLE = yes
BOOTMAGIC_ENABLE = yes

RGB_MATRIX_ENABLE = yes

# Optimizations
LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no

SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MUSIC_ENABLE = no